### ISSUE TITLE
SharePoint authentication using ClientID and secret

### ISSUE THREAD

**Issue by obrassard** [obrassard/action-sharepoint-publish#14]
### Suggestion received by email :

It should be possible to authenticate with Client ID and Secret (App Principal on Sharepoint) in place of Username and password.
 
Seems like security is tying down more and more Microsoft products with using normal username and passwords.

---

In its current form the action only supports login with a username and password. However it seems that the package used to upload files to SharePoint (spsave) supports authentication with a clientId as seen here : https://github.com/s-KaiNet/spsave/blob/master/docs/Recipes.md

So we would have to update the action in order to add new parameters to support this type of authentication.

**Comment by purplebearddan** [comment]
I have done this for my company and will send a pull request now
