### ISSUE TITLE
Use the action to deploy an angular build to SharePoint library by deleting the files from library and checking in again all files

### ISSUE THREAD

**Issue by ashishpCACTUS** [obrassard/action-sharepoint-publish#8]
Apologies I am new to the github action world so I am a little confused. 

Like harsohailB, I want to use this action to deploy an Angular build to a SP library by deleting all the existing files and copying new files and checking-in the files. 

I could follow  https://github.com/harsohailB/react-app-sp-deployment to do a folder level deployment by just deploying the build folder I can deploy the dist folder in angular case. I was also planning to use the https://www.npmjs.com/package/sppurge package to purge the files first in the SP library and while uploading the files use the check-in option of spsave action so files are checked in as soon as they are uploaded. 

So after comparing the two actions, I could see changes to the be done in the index.js and the package.json (to include sppurge) library to accomplish my requirement.  I am planning to fork this action and perform these two actions. 

As I am new to this world, just wanted to check if the above is sane or I am missing some steps. 

Thanks in advance

**Comment by obrassard** [comment]
Sorry for the late reply! I've never used the packages you mention, however it sounds like a good idea.
