### ISSUE TITLE
Sharepoint Access Blocked by Conditional Access Policies

### ISSUE THREAD

**Issue by macso-hwangoh** [obrassard/action-sharepoint-publish#9]
Hello, I was wondering if there is any setup required on the Sharepoint side to allow uploading to a Sharepoint site. When including your suggested GitHub YAML workflow file, I obtained this error:

[23:13:32] spsave: Error occured:
[23:13:32] spsave: <S:Fault>
  <S:Code>
    <S:Value>S:Sender</S:Value>
    <S:Subcode>
      <S:Value>wst:FailedAuthentication</S:Value>
    </S:Subcode>
  </S:Code>
  <S:Reason>
    <S:Text xml:lang="en-US">Authentication Failure</S:Text>
  </S:Reason>
  <S:Detail>
    <psf:error xmlns:psf="http://schemas.microsoft.com/Passport/SoapServices/SOAPFault">
      <psf:value>0x80048823</psf:value>
      <psf:internalerror>
        <psf:code>0x80048823</psf:code>
        <psf:text>AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance.</psf:text>
      </psf:internalerror>
    </psf:error>
  </S:Detail>
</S:Fault>

**Comment by obrassard** [comment]
Hello, that's a good question. It's been I while since I used this action on my side, but as far as I remember It seems to me that I didn't need to configure anything special on my SharePoint tenant. Although it might depend of your organization policies.

**Comment by macso-hwangoh** [comment]
Hey thanks for the prompt reply and thanks for writing this cool app!

I've been looking into it now and have yet to find an answer. It seems that modifying the access policies for Sharepoint is not straightforward and also does not appear by default in the "Sharepoint admin center" so this could be a potentially common blockage for your app. 

I won't be continuing this thread for sometime (at least a week) but if I find something I'll be sure to mention it here :).

**Comment by obrassard** [comment]
Thanks @macso-hwangoh !
